-- 코드를 입력하세요
SELECT date_format(S.SALES_DATE, '%Y-%m-%d') AS SALES_DATE, S.PRODUCT_ID, S.USER_ID, S.SALES_AMOUNT
FROM (
    SELECT SALES_DATE, PRODUCT_ID, USER_ID, SALES_AMOUNT
    FROM ONLINE_SALE
    
    UNION ALL
    
    SELECT SALES_DATE, PRODUCT_ID, NULL AS USER_ID, SALES_AMOUNT
    FROM OFFLINE_SALE
) AS S
WHERE S.SALES_DATE LIKE '2022-03%'
ORDER BY S.SALES_DATE, S.PRODUCT_ID, S.USER_ID;