-- 코드를 입력하세요
SELECT B.USER_ID, B.NICKNAME, SUM(A.PRICE) AS TOTAL_SALES
FROM USED_GOODS_BOARD AS A INNER JOIN USED_GOODS_USER AS B
ON A.WRITER_ID = B.USER_ID AND A.STATUS = 'DONE'
GROUP BY A.WRITER_ID
HAVING SUM(A.PRICE) >= 700000
ORDER BY SUM(A.PRICE);