-- 코드를 입력하세요
SELECT PRODUCT_CODE, SUM(P.PRICE * S.SALES_AMOUNT) AS SALES
FROM PRODUCT AS P INNER JOIN OFFLINE_SALE AS S
ON P.PRODUCT_ID = S.PRODUCT_ID
GROUP BY P.PRODUCT_ID
ORDER BY SUM(P.PRICE * S.SALES_AMOUNT) DESC, PRODUCT_CODE;